### ISSUE TITLE
Resizing big videos

### ISSUE THREAD

**Issue by chaosmonger** [georgepaterson/jquery-videobackground#40]
I'm sorry, maybe it's a noob question, but I'm a noob.
Anyway, I'm having some issues using your code with video 1920x1080 on a screen 1400x900.
Basically, both in Firefox and Chrome the video is not resizing to fit the screen. It stay 1920x1080 so I can see only a portion of it.
Trying with a video half size it works, but since I'm a filmmaker and I wanna keep the video on a FullHD resolution, expecialy for screens with hi-def, I would like to solve the problem without changing resolution of the video.
Any suggestions? What's the problems? Is it a bug? Or...!?

**Comment by chaosmonger** [comment]
more infos:
the video size is 2MB and last 4 seconds (loop).
the poster image that appear few seconds before the video is also not resized.

**Comment by georgepaterson** [comment]
I've not encountered the problem, do you have an URL i can see it in action?

If not, i got a GoPro recently and will be tinkering about with hi-res video.

**Comment by chaosmonger** [comment]
You can try here:
http://www.chaosmonger.com
The video is 1920x1080. I made a test resizing the video to 960x540 and it works.
Now I can see only a portion...

**Comment by chaosmonger** [comment]
Any news?!?!

**Comment by georgepaterson** [comment]
Looking at a 1920 screen versus a 1440 screen, it looks like the video plays at it's native pixel size. The 1920 screen get almost all the video, the 1440 gets a relative portion. The 1920 screen gets almost all because it loses some space for the browser chrome.

The video doesn't act like a background image as it doesn't have the full browser rendering support for rescaling.

There isn't a fix for this, i can only advise setting a a lower resolution video as the video can proportionally scale upwards.

**Comment by chaosmonger** [comment]
Thanks... That's bad... So the only option is to use lower res.

thank you anyway!

**Comment by georgepaterson** [comment]
Cool, good luck.
